name: yahtzee-java # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Java version of Yahtzee
description: |
  Java version of Yahtzee

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  yahtzee_icon.png
title: Yahtzee (Java)

apps:
  yahtzee:
    command: startyahtzee
parts:
  yahtzee:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      yahtzee: build/
      yahtzee.1: man/man1/

architectures:
  - build-on: amd64

